import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pomodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={rubik.className}>
      <ThemeProvider>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
